#!/bin/sh
#/usr/lib/systemd/systemd --user &
# Configure X
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

# Start a D-Bus session
#source /etc/X11/xinit/xinitrc.d/30-dbus
# Start GNOME keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets ssh)
# You probably need to do this too:
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID
xset s off
setxkbmap -option terminate:ctrl_alt_bksp

