#!/bin/bash

export EDITOR="nvim";
export TERMINAL="kitty";
export BROWSER="firefox";
export READER="zathura";
export FILE="ranger";
export SUDO_ASKPASS="$HOME/bin/tools/dmenupass";
export PIX="$HOME/.pix/";
export DOTFILES_PATH="$HOME/.dotfiles";

# History is in the past
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
export HISTIGNORE="&:ls:[bf]g:exit:reset:clear:cd*:date:* --help";

# mac exports
if $_ismac; then
  export HOMEBREW_AUTO_UPDATE_SECS=86400;
  export HOMEBREW_NO_ANALYTICS=true;
  export HOMEBREW_INSTALL_BADGE="(ʘ‿ʘ)";
  export HOMEBREW_BUNDLE_FILE_PATH=~/.homebrew/Brewfile;
fi

# For the fuzzy finder
if _have fzf; then
  export FZF_DEFAULT_OPTS='--color=bg+:24 --reverse';
fi

export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X";

export DBUS_SESSION_BUS_ADDRESS
DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/user/$(id -u)/bus;

# hidpi for gtk apps
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export QT_DEVICE_PIXEL_RATIO=2

#TODO: Let's understand this more
#export DOCKER_CONTENT_TRUST=1

# if it's an ssh session export GPG_TTY
if [[ -n "$SSH_CLIENT" ]] || [[ -n "$SSH_TTY" ]]; then
    GPG_TTY=$(tty)
    export GPG_TTY
fi

# set xdg data dirs for dmenu to source
export XDG_DATA_DIRS=/usr/share/

# custom ip var
[[ -f "$HOME/.myip" ]] && export MYIP=$(cat "$HOME/.myip")

# raw AWS keys stored and exported in separate file
_source "$HOME/.aws_keys"

export GTAGSCONF=/usr/local/share/gtags/gtags.conf
export GTAGSLABEL=ctags

if [ -e ~/.dpi ]; then
  source ~/.dpi
fi

if [ -d ~/.pyenv ]; then
  export PYENV_ROOT="$HOME/.pyenv"
fi

#Mac git completion
if $_ismac; then
  if [ -f `brew --prefix`/etc/bash_completion.d/git-completion.bash ]; then
    . `brew --prefix`/etc/bash_completion.d/git-completion.bash
  fi
fi
