#!/usr/bin/env sh

# ===== Variables ========================
gaps_top="20"
gaps_bottom="24"
gap_left="4"
gaps_right="4"
gaps_inner="4"

normal_border_color="010101"
focused_border_color="808080"
preselect_border_color="2d74da"

# ======= Status Bar =================================
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Iosevka:Bold:14.0"
yabai -m config status_bar_icon_font         "Iosevka:Regular:14.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        


# ======= Tiling settings ============================
yabai -m config layout                       bsp

yabai -m config top_padding                  "${gaps_top}"
yabai -m config bottom_padding               "${gaps_bottom}"
yabai -m config left_padding                 "${gaps_left}"
yabai -m config right_padding                "${gaps_right}"
yabai -m config window_gap                   "${gaps_inner}"

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                float

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# ========= Border settings ===========================
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   "0xE0${focused_border_color}"
yabai -m config insert_window_border_color   "0xE0${preselect_border_color}"
yabai -m config normal_window_border_color   "0x00${normal_border_color}"

# rules
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Google Chrome" app="^Google Chrome$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off
yabai -m rule --add app="Firefox" manage=off
yabai -m rule --add app="RubyMine" manage=off
yabai -m rule --add app="PyCharm" manage=off
yabai -m rule --add app=Preview manage=off border=off
yabai -m rule --add label="Franz" app="^Franz$" manage=on display=2
yabai -m rule --add label="YakYak" app"^YakYak$" manage=on display=2

yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-primary-jsx\"'"
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-secondary-jsx\"'"

yabai -m signal --add event=window_focused \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-primary-jsx\"'"
yabai -m signal --add event=window_focused \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"nibar-spaces-secondary-jsx\"'"

#YABAI_CERT=yabai-cert sh -c "$(curl -sSL "https://git.io/update-yabai")" &

echo "yabai configuration loaded.."
