#!/bin/sh
/usr/lib/systemd/systemd --user &
# Configure X
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap
xscreensaver -no-splash &
xsetroot -cursor_name left_ptr 
#wallpaper.sh &

# Start a D-Bus session
source /etc/X11/xinit/xinitrc.d/30-dbus
# Start GNOME keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets ssh)
# You probably need to do this too:
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID
xset s off
setxkbmap -option terminate:ctrl_alt_bksp


# Start the apps
#tray &
udiskie --tray &
urxvtd -q -f -o
dropboxd &  #commented out for openbox
nm-applet &   #commented out for openbox
parcellite &
pasystray &
redshiftgui &
synergys &
calibre &
pidgin &
/home/dnewman/.bin/ncmpc &

