#+TITLE: Daniel Newman's Doom Emacs Configuration
#+AUTHOR: Daniel Newman
#+STARTUP: showeverything
#+PROPERTY: header-args :tangle yes :cache yes :results silent :padline no
#+EXPORT_FILE_NAME: README

* Configuration

** Personal Information

*** Set full name
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Daniel Newman")
#+END_SRC

*** Set email address
#+BEGIN_SRC emacs-lisp
(setq user-mail-address "dan@danlovesprogramming.com")
#+END_SRC

** Core

*** Load user functions
Keeping user defined functions in a separate file
#+BEGIN_SRC emacs-lisp
(load! "+functions")
(load! "+theming")
(load! "+commands")
#+END_SRC

*** Keybinds
**** Global Keybinds
***** Leader keybinds
#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix "TAB"
       :desc "Rename workspace"       "r"  #'+workspace/rename)
      (:prefix "f"
       :desc "Find remote file"      "R" #'counsel-tramp
       :desc "Find file in dotfiles" "t" #'+daniel/find-in-dotfiles
       :desc "Browse dotfiles"       "T" #'+daniel/browse-dotfiles)
      (:prefix "t"
       :desc "Rainbow mode" "r" #'rainbow-mode))
#+END_SRC

** Doom fonts
Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

+ `doom-font'
+ `doom-variable-pitch-font'
+ `doom-big-font' -- used for `doom-big-font-mode'; use this for
presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:
#+BEGIN_SRC emacs-lisp
(when (equal system-type 'gnu/linux)
  (setq doom-font (font-spec :family "JetBrains Mono" :size 20 :weight 'normal)
        doom-big-font (font-spec :family "JetBrains Mono" :size 22 :weight 'normal)))
(when (equal system-type 'windows-nt)
  (setq doom-font (font-spec :family "InputMono" :size 18)
        doom-big-font (font-spec :family "InputMono" :size 22)))
#+END_SRC

For terminal emacs usage, I want to try out this font
#+begin_src emacs-lisp
(when (equal (window-system) nil)
  (and
   (bind-key "C-<down>" #'_org/insert-item-below)
   (setq doom-theme nil)
   (setq doom-font (font-spec :family "Roboto Mono" :size 20))))
#+end_src
** Doom Theme
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-tomorrow-night)
(map! :leader
      :desc "Load new theme"
      "h t" #'counsel-load-theme)
(after! doom-themes
  (setq doom-neotree-file-icons t))
#+END_SRC

** EVALUATE ELISP EXPRESSIONS
Changing some keybindings from their defaults to better fit with Doom Emacs, and to avoid conflicts with my window managers which sometimes use the control key in their keybindings.  By default, Doom Emacs does not use 'SPC e' for anything, so I choose to use the format 'SPC e' plus 'key' for these (I also use 'SPC e' for 'eww' keybindings).

| COMMAND         | DESCRIPTION                                    | KEYBINDING |
|-----------------+------------------------------------------------+------------|
| eval-buffer     | /Evaluate elisp in buffer/                       | SPC e b    |
| eval-defun      | /Evaluate the defun containing or after point/   | SPC e d    |
| eval-expression | /Evaluate an elisp expression/                   | SPC e e    |
| eval-last-sexp  | /Evaluate elisp expression before point/         | SPC e l    |
| eval-region     | /Evaluate elisp in region/                       | SPC e r    |

#+Begin_src emacs-lisp
(map! :leader
      :desc "Evaluate elisp in buffer"
      "e b" #'eval-buffer
      :leader
      :desc "Evaluate defun"
      "e d" #'eval-defun
      :leader
      :desc "Evaluate elisp expression"
      "e e" #'eval-expression
      :leader
      :desc "Evaluate last sexpression"
      "e l" #'eval-last-sexp
      :leader
      :desc "Evaluate elisp in region"
      "e r" #'eval-region)
#+END_SRC

** Lsp
#+BEGIN_SRC emacs-lisp
(use-package! lsp-mode
  :hook
  (haskell-mode . lsp)
  (python-mode . lsp)
  (rustic-mode . lsp)
  (rust-mode . lsp)
  (reason-mode . lsp)
  :config
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-stdio-connection "reason-language-server")
                    :major-modes '(reason-mode)
                    :notification-handlers (ht ("client/registerCapability" 'ignore))
                    :priority 1
                    :server-id 'reason-ls))
  :commands
  lsp)

(use-package! lsp-ui
  :commands
  lsp-ui-mode)

(use-package! company-lsp
  :commands company-lsp)
#+END_SRC

** Org Mode
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads! Doom Emacs uses 'SPC t' for "toggle" commands, so I choose 'SPC t t' for toggle-truncate-lines.
#+BEGIN_SRC emacs-lisp
(use-package! org
  :config
  (setq org-agenda-files (file-expand-wildcards "~/Documents/org/*.org"))
  (setq org-directory (expand-file-name "~/Documents/org"))
  (setq org-cycle-separator-lines 1)
  (defvar +org-dir (expand-file-name "~/Documents/org"))
  (setq org-capture-templates
        '(("c" "Code Task" entry (file+headline "~/Documents/org/todo.org" "Coding Tasks")
           "* TODO %?\n Entered on: %U - %a\n")
          ("t" "Task" entry (file+headline "~/Documents/org/todo.org" "Tasks")
           "* TODO %?\n Entered on: %U")
          ("n" "Note" entry (file+datetree "~/Documents/org/todo.org")
           "* %?\n\n"))))
#+END_SRC

** Neotree
#+BEGIN_SRC emacs-lisp
(after! neotree
  (setq doom-themes-neotree-file-icons 'icons)
  (setq doom-themes-neotree-enable-file-icons 'icons)
  (setq neo-theme 'icons))
#+END_SRC

** Line numbers
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type t)
(map! :leader
      :desc "Toggle truncate lines"
      "t t" #'toggle-truncate-lines)
#+END_SRC

** Indent guides
*** Define package
#+BEGIN_SRC emacs-lisp
(use-package! highlight-indent-guides
  :hook (prog-mode . highlight-indent-guides-mode))
#+END_SRC
*** Use characters for indent guides
#+BEGIN_SRC emacs-lisp
(after! highlight-indent-guides
  (setq highlight-indent-guides-method 'character))
#+END_SRC
*** Use responsive highlights
Highlight indentation based on current line
#+BEGIN_SRC emacs-lisp
(after! highlight-indent-guides
  (setq highlight-indent-guides-character ?\┆))
#+END_SRC
*** Set colors
#+BEGIN_SRC emacs-lisp
(after! highlight-indent-guides
  (setq highlight-indent-guides-auto-enabled 'top)
  (set-face-attribute 'highlight-indent-guides-odd-face nil :inherit 'highlight-indentation-odd-face)
  (set-face-attribute 'highlight-indent-guides-even-face nil :inherit 'highlight-indentation-even-face)
  (set-face-foreground 'highlight-indent-guides-character-face (doom-color 'base5)))
#+END_SRC

** Bookmarks and Buffers
#+BEGIN_SRC emacs-lisp
(map! :leader
      :desc "List bookmarks"
      "b L" #'list-bookmarks
      :leader
      :desc "Save current bookmarks to bookmark file"
      "b w" #'bookmark-save)
#+END_SRC

** DIRED
Dired is the file manager within emacs. Below, I setup keybindings for image previews (peep-dired). Doom Emacs does not use 'SPC d' for any of its keybindings, so I've chosen the format of 'SPC d' plus 'key'.

| COMMAND                                   | DESCRIPTION                                     | KEYBINDING |
|-------------------------------------------+-------------------------------------------------+------------|
| dired                                     | /Open dired file manager/                         | SPC d d    |
| dired-jump                                | /Jump to current directory in dired/              | SPC d j    |
| (in dired) peep-dired                     | /Toggle image previews within dired/              | SPC d p    |
| (in dired) dired-view-file                | /View file in dired/                              | SPC d v    |
| (in dired) dired-up-directory             | /Go up in the directory tree/                     | h          |
| (in dired) dired-find-file                | /Go down in the directory tree (or open if file)/ | l          |
| (in peep-dired-mode) peep-dired-next-file | /Move to next file in peep-dired-mode/            | j          |
| (in peep-dired-mode) peep-dired-prev-file | /Move to previous file in peep-dired-mode/        | k          |

#+BEGIN_SRC emacs-lisp
(map! :leader
      :desc "Dired"
      "d d" #'dired
      :leader
      :desc "Dired jump to current"
      "d j" #'dired-jump
      (:after dired
        (:map dired-mode-map
         :leader
         :desc "Peep-dired image previews"
         "d p" #'peep-dired
         :leader
         :desc "Dired view file"
         "d v" #'dired-view-file)))
;; Make 'h' and 'l' go back and forward in dired. Much faster to navigate the directory structure!
(evil-define-key 'normal dired-mode-map
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
;; If peep-dired is enabled, you will get image previews as you go up/down with 'j' and 'k'
(evil-define-key 'normal peep-dired-mode-map
  (kbd "j") 'peep-dired-next-file
  (kbd "k") 'peep-dired-prev-file)
(add-hook 'peep-dired-hook 'evil-normalize-keymaps)
;; Get file icons in dired
(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
;; With dired-open plugin, you can launch external programs for certain extensions
;; For example, I set all .png files to open in 'sxiv' and all .mp4 files to open in 'mpv'
(setq dired-open-extensions '(("gif" . "sxiv")
                              ("jpg" . "sxiv")
                              ("png" . "sxiv")
                              ("mkv" . "mpv")
                              ("mp4" . "mpv")))
#+END_SRC

** Miscellaneous Configuration
Here are some additional functions/macros that could help you configure Doom:

- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
this file. Emacs searches the `load-path' when you load packages with
`require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.
