# Colors (Lucius Light)
colors:
  # Default colors
  primary:
    background: '0xeeeeee'
    foreground: '0x444444'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    cursor: '0x5f87af'

  # Normal colors
  normal:
    black:   '0x444444'
    red:     '0xaf0000'
    green:   '0x008700'
    yellow:  '0xaf5f00'
    blue:    '0x005faf'
    magenta: '0x870087'
    cyan:    '0x008787'
    white:   '0xeeeeee'

  # Bright colors
  bright:
    black:   '0x444444'
    red:     '0xaf0000'
    green:   '0x008700'
    yellow:  '0xaf5f00'
    blue:    '0x005faf'
    magenta: '0x870087'
    cyan:    '0x008787'
    white:   '0xeeeeee'
