# Colors (Lucius Dark)
colors:
  # Default colors
  primary:
    background: '0x303030'
    foreground: '0xd7d7d7'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    cursor: '0x87afd7'

  # Normal colors
  normal:
    black:   '0x303030'
    red:     '0xff5f5f'
    green:   '0xafd787'
    yellow:  '0xd7d7af'
    blue:    '0x87d7ff'
    magenta: '0xd7afd7'
    cyan:    '0x87d7af'
    white:   '0xd7d7d7'

  # Bright colors
  bright:
    black:   '0x303030'
    red:     '0xff5f5f'
    green:   '0xafd787'
    yellow:  '0xd7d7af'
    blue:    '0x87d7ff'
    magenta: '0xd7afd7'
    cyan:    '0x87d7af'
    white:   '0xd7d7d7'
